### ISSUE TITLE
Replace `char *` to `static char * const`

### ISSUE THREAD

**Issue by Ullaakut** [NySwann/NCurses_Sokoban#9]
I'm not sure if you will get a notification / email on an already merged commit, so here is an issue for it

![screen shot 2016-12-29 at 10 07 39](https://cloud.githubusercontent.com/assets/6976628/21540315/cbab0268-cdae-11e6-9e68-01da88a1985d.png)

I'd recommend always to try to use const variables as much as possible, even though most compilers are already doing the job for you internally and it might seem to be quite useless because of this, it will actually make it easier to understand your code: for example, if someone sees a variable that is not const, he probably assumes it will be changed later on, which might be confusing if it's not the case.

**Comment by NySwann** [comment]
I agree for the "const" modifier, it seems logic. But for the "static" modifier, i am confused. I thought that this modifier was used in order to declare a field with a scope limited inside the current file. That's why i feel very strange about writing this inside a header file.. But maybe ther's a reason and i simply don't get it!

Anyway, thanks for opening all thos issues and your very precise code review, i'm very grateful.

PS : "const variable" means "constant variable", it makes no sense :P

**Comment by Ullaakut** [comment]
Well IMO it should be in main.c and the usage function should be too if it's not already the case, then the variable is declared in your main.c as a static :) 

I didn't quite get your PS though, what makes no sense?

**Comment by NySwann** [comment]
Global variables are allowed, since their usage are justified and their names start with "gl_" according to the epitech norm. I feel that using a global const is the right choice for this special case. Error handing is important, and I think that having nice error messages maybe a good point too. So I'm going with the `const char *gl_binary_name` :)
